package com.manage.sys.config.status;

public  enum PURCHASEORDER_STATUS_CODE {
    PURCHASEORDER_STATUS_CODE_INITIALIZATION(0),

    PURCHASEORDER_STATUS_CODE_ORDERTYPE_PERSON(0),
    PURCHASEORDER_STATUS_CODE_ORDERTYPE_COMPANY(1),
    PURCHASEORDER_STATUS_CODE_ORDERTYPE_GOVERNMENT(2),

    PURCHASEORDER_STATUS_CODE_REVIEWTYPE_REVIEWING(0),
    PURCHASEORDER_STATUS_CODE_REVIEWTYPE_PASSREVIEW(1);
    private final int value;

    PURCHASEORDER_STATUS_CODE(final int newValue){value=newValue;}

    public int getValue() {
        return value;
    }
}
